### ISSUE TITLE
How do I get a type from schema/validator?

### ISSUE THREAD

**Issue by hasparus** [typeofweb/schema#31]
Hey, a friend just shared this library with me. It looks pretty cool, and the benchmarks seem impressive :)

Reading the README I'm not sure how do I extract a type from validator?

Looking at the examples, I'd guess that this is possible, but it seems to be missing from the README. (I'm sorry if it's there and I missed it)

```ts
type Person = FromSchema<typeof personSchema>
```

**Comment by stepaniukm** [comment]
Hi, to receive the type of schema you do something like this:
```ts
import type { TypeOf } from "@typeofweb/schema"

const personSchema = object({...})

type Person = TypeOf<typeof personSchema>
```

**Comment by stepaniukm** [comment]
https://github.com/typeofweb/schema/issues/33 Opened to fill the docs with information on `TypeOf` and other type helpers

**Comment by hasparus** [comment]
Thanks

**Comment by mmiszy** [comment]
The missing docs are now added here: https://typeofweb-schema.vercel.app/
