### ISSUE TITLE
Object schema validation does not convert its values

### ISSUE THREAD

**Issue by Aliath** [typeofweb/schema#49]
As is it presented in documentation object schema validation should convert its values into the expected ones, for instance: strings into numbers. Instead of this we get error with invalid type.

Version: 0.6.1
Use case: https://schema.typeofweb.com/docs/validate#example
Expected result:
```js
{
    dateFrom: new Date('2020-10-15T00:00:00.000Z'), // date instance
    dateTo: new Date('2020-10-15T00:00:00.000Z'), // date instance
    resultsPerPage: 10 // number
}
```
Received result:
```ValidationError: Invalid type! Expected { dateFrom: Date, dateTo: Date, resultsPerPage: number } but got {"dateFrom":"2020-10-15","dateTo":"2020-10-15","resultsPerPage":"10"}!```

**Comment by mmiszy** [comment]
Cannot reproduce it in 0.7.0. Added a test case https://github.com/typeofweb/schema/commit/8d15def03cf336ae1aaed04d088b2e7815848204

**Comment by mmiszy** [comment]
@all-contributors please add @Aliath for bug
