### ISSUE TITLE
sideEffects is invalid in package.json declaration

### ISSUE THREAD

**Issue by o-alexandrov** [typeofweb/schema#52]
## Problem

The following declaration in the `package.json` is invalid.

```json
{
  "sideEffects": false
}
```

The `@typeofweb/schema` library does have side effects and cannot be tree shaked (dead code removed) when **not used** but other variables are imported from the same module containing variables from `@typeofweb/schema`.

## How to reproduce the issue

If you use:
- [webpack's built-in stats](https://webpack.js.org/configuration/stats/)
- [statoscope](https://github.com/smelukov/statoscope) or any other tool to examine the stats

You would see `@typeofweb/schema` is identified as [having a side effect here](https://github.com/typeofweb/schema/blob/refinements/src/errors.ts#L4).

<details><summary>Screenshot</summary>
<img width="858" alt="Screen Shot 2021-03-19 at 8 06 21 PM" src="https://user-images.githubusercontent.com/9992724/111854993-410f9180-88f0-11eb-87e9-580c00dadbba.png">

</details>

## Expected behavior

Class `ValidationError` shouldn't have side effects

**Comment by mmiszy** [comment]
Where's the side effect?

**Comment by o-alexandrov** [comment]
@mmiszy I think the declaration of the Class is considered as a side effect here.
Unfortunately, I'm not an expert in the always changing state of side effects related to minifiers, but afaik:
- class cannot be safely dead code removed because terser is unable to analyze whether the class' properties are dynamically accessed or not
  - Facebook wrote a better explanation on Classes [in their React.js blog](https://reactjs.org/docs/hooks-intro.html#classes-confuse-both-people-and-machines)
  
Created a reproducible [example here](https://github.com/typeofweb/schema/pull/55).
Please pull, install deps & run:
`yarn example`

To see what will be dead code removed in the created `src/example.js`.
- the `ValidationError` will stay

**Comment by mmiszy** [comment]
It seems to be unrelated to classes – the same happens for functions as well. Not sure how to tell webpack or terser that this package doesn't have ANY side effects apart from `sideEffects: true` in package.json.

**Comment by o-alexandrov** [comment]
@mmiszy yes, I've seen this issue related to functions as well.
But the error from the screenshot above using `webpack`'s stats & a stats analyzer, such as `statoscope`:
- indicates what webpack + terser don't like:
  - `Statement (ClassDeclaration) with side effects in source code at 27:0-42:1`

I'll try to experiment with `ValidationError` switching it to a pure function approach later this week.
- then rerunning bundling in a real project and record a `.gif` with an outcome
  - I understand creating a programmatic invocation of `webpack` + `terser` as a reproducible example would have been clearer, but I hope a `.gif` would still be ok, if it solves the issue

**Comment by o-alexandrov** [comment]
The error was on my side.
Setting terser's [compress.passes](https://github.com/terser/terser#compress-options) more than `1` got the ValidationError to be removed when unused.
