### ISSUE TITLE
Bug in Performance graphics ?

### ISSUE THREAD

**Issue by rgrebski** [typeofweb/schema#65]
I think you have a bug in Percentage column of performance test.
If avg for your lib is 0.5us and zod is 100x slower (53us) it should be -10000% ?

![image (15)](https://user-images.githubusercontent.com/12778116/113753541-81537a00-970e-11eb-8844-feb794ed725a.png)

**Comment by mmiszy** [comment]
Nope. Everything is correct:

`1 / ( ( 1 / 0.517us ) * ( 1 - 0.9903 ) ) ~= 53us`
